spring:
  application:
    name: ms-logistics-query
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:example@localhost:27017/db_queries?authSource=admin}
  redis:
    host: ${SPRING_DATA_REDIS_HOST:localhost}
    port: ${SPRING_DATA_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: 8082

logging:
  level:
    pe.edu.galaxy.logistics: DEBUG
